spring.application.name=farm

spring.datasource.url=jdbc:postgresql://localhost:5431/dailyFarm
spring.datasource.username=admin
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.show-sql=true

#docker run --name my_postgres -e POSTGRES_DB=dailyFarm -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=12345 -p 5431:5432 -d postgres
#docker ps
#docker start my_postgres
#docker exec -it my_postgres psql -U admin -d dailyFarm

#???? ?????? ?? ????? ?? ?????? ?????, ??????? ??
spring.security.user.name=admin
spring.security.user.password=admin

